### ISSUE TITLE
Select if attending before paying should be allowed

### ISSUE THREAD

**Issue by Torrib** [CasualGaming/studlan#108]
Add a boolean field to the lan to decide if it should be possible for users to sign upp for the lan before paying or not.

**Comment by larserikgk** [comment]
Is this a feature we really want? As of now, users have to sign up before paying. Do you mean we should check payment before users can sign up for competitions?

**Comment by Torrib** [comment]
Mean that we should be able to select if the lan should have a separate sign up or not. Signing up before paying makes sense on the small lans but not necessarily on the big ones.

**Comment by Torrib** [comment]
The number of people that does not prepay is so low that this issue will not be fixed
