### ISSUE TITLE
Adding tournament timeline-tab under "Competitions" tab

### ISSUE THREAD

**Issue by KnasKnas** [CasualGaming/studlan#140]
### Feature or Bug?
- [x] Feature
- [ ] Bug
### Feature

A tab under "Competitions/Konkurranser" on both studlan.no and trondelan.no that lets people view a detailed timetable for all competitions instead of having to navigate the front-page every time one wants to find this out
#### What would you like?

Already described in feature, allthough I did not mention that it should be viewed as something like an excel-document.... something that is easily understood and still has enough information.
#### How should it work?

Either by using ajax or something to mimic an excel-drive-document within the page, or simply by uploading the excel-file to display on the page.
#### Checklist
- [ ] Create subpage under "Competitions/Konkurranser" tabs
- [ ] Set a window-size for which to display the timetable for competitions for the current event/LAN
- [ ] Implement functions that lets you either upload a timetable or use a link that opens the timetable within the set window
#### Description

A short summary of what already described above:
- tabs underneath competitions/konkurranser that opens a window regadring timeline of tournaments
- opens a window with set details of timeline
- either uploaded excel or in-page view of excel/other good timeline-tool

**Expected behavior**

**Current behaviour**

**Possible Solution**
#### Steps to reproduce:
1. Open ...
2. Click ...
3. $
#### Environment

Operating system:
Arch:
Python version:
Database:

**Comment by larserikgk** [comment]
I like this idea, and we should try to implement it before TrøndeLan 2016 if possible. My immediate thought is that integrating Google Calendar is probably the easiest solution. We could also make our own models and layout from scratch, but this would require considerable more work.
