### ISSUE TITLE
Update vagrant file

### ISSUE THREAD

**Issue by larserikgk** [CasualGaming/studlan#160]
### Feature or Bug?
- [x] Feature

### Feature
Strip this part away if you are reporting a bug.

#### What would you like?
Vagrant file should reflect the new project directory structure.

#### How should it work?
The bootstrapping script should run without errors.

#### Checklist

- [ ] Fix pip install path
- [ ] Fix removal of setuptools after install
- [ ] Use postgresql as dev backend

**Comment by larserikgk** [comment]
Sqlite should be replaced with postgre in development to ensure identical environments. Look at https://github.com/jackdb/pg-app-dev-vm/blob/master/Vagrant-setup/bootstrap.sh for an example of how to bootstrap postgresql.

**Comment by HON95** [comment]
Vagrant has been removed. Close issue?
