### ISSUE TITLE
Migration of postman gives error

### ISSUE THREAD

**Issue by larserikgk** [CasualGaming/studlan#166]
### Feature or Bug?
- [ ] Feature
- [x] Bug

#### Description
Migration of the database from the last release to the newest commits gives migrations errors for the postman module.

**Expected behavior**
Migrations should complete without error.

**Current behaviour**
Migrations give the 

> trondelan_dev_1  | django.db.utils.ProgrammingError: relation "postman_message" already exists
error. The site still runs, but we should fix migration errors before we publish a new release. This only happens in postgre, not in sqlite.

**Possible Solution**
Initial research shows that using --fake with the migration command might ignore the fact that the tables exists and stop the error from appearing, but we should find the cause of the error.

#### Environment
Python version: 2.7
Database: Postgresql

**Comment by MathiasFl** [comment]
Mener at det fikses ved å bruke en nyere versjon av postman. Skal sjekke :)

**Comment by larserikgk** [comment]
As described in #170, this error occurs when Django tried to apply 'postman.0001_initial'. This is a migration within the postman app. [Other issues](https://github.com/WeblateOrg/weblate/issues/587) in the postman tracker seem to indicate that running [migreate --fake-inital](https://docs.djangoproject.com/en/1.11/topics/migrations/#initial-migrations) might solve our problem.

**Comment by MathiasFl** [comment]
Commit d36c304cbfe5294295a536ab62e577411a3c9772 resolved this issue
