### ISSUE TITLE
URL redirects internaly on all links

### ISSUE THREAD

**Issue by MathiasFl** [CasualGaming/studlan#169]
### Feature or Bug?
- [ ] Feature
- [x] Bug

### Bug
for a link to example discord invite "https://discord.gg/FTENjrqs" in url markdown to not add as a sub path to as trondelan.no/https://discord.gg/FTENjrqs

#### Description

**Expected behavior**
Link text "Discord app" should link to -> https://discord.gg/FTENjrqs

**Current behaviour**
Link text "Discord app" links to https://trondelan.no/https%3A%2F%2Fdiscord.gg%2FTENjrqs

**Possible Solution**
Issue comes from Markdown rules in settings, have fixed in other versions just putting it down so i don't forgett

#### Steps to reproduce:

1. Open trondelan.no
2. Click on any markdown made links
3. $$$

#### Environment
Operating system: Live enviroment

**Comment by larserikgk** [comment]
Would be sweet to fix this before TrøndeLan 2017
