### ISSUE TITLE
Creation of alias type on dev is broken

### ISSUE THREAD

**Issue by larserikgk** [CasualGaming/studlan#170]
### Feature or Bug?
- [ ] Feature
- [x] Bug

#### Description
Creation of alias type on dev.trondelan.no gives IntegrityError. This is related to #164. Unable to reproduce this bug on local machine.

**Expected behavior**
Creation of alias type should complete sucessfully.

**Current behaviour**
Creation of alias type in admin panel gives IntegrityError due to a required value in the database being NULL.

**Possible Solution**
Either there is a bug in #164, or migrations have not been run correctly on dev.trondelan.no.

#### Steps to reproduce:

1. Open admin panel on dev.trondelan.no
2. Create new alias type connected to at least one Activity

#### Environment
dev.trondelan.no

#### Stacktrace/Code/Screenshot
[Screenshot](blob:http://imgur.com/d0bdd4c4-cf00-48cd-86a3-bce8ae3aebf6)

**Comment by larserikgk** [comment]
Would be helpful if you could confirm that this is not an issue of migrations not being run in staging @kradalby, when your vaction is over :)

**Comment by MathiasFl** [comment]
migration works on localhost for me, as well as adding and removing alias.

**Comment by larserikgk** [comment]
Did the migration succeed using postgre, or are you using sqlite for development as well? I suspect postgre might not support the kind of migration specified in #164

**Comment by MathiasFl** [comment]
Issues stems from previous master migration:
[Loggfile](https://gist.github.com/kradalby/2c7b0c8c5eb9f5261c7b46fbb8ffaf10)

**Comment by MathiasFl** [comment]
Commit d36c304cbfe5294295a536ab62e577411a3c9772 resolved this issue
