### ISSUE TITLE
Typeahead in team invitations

### ISSUE THREAD

**Issue by larserikgk** [CasualGaming/studlan#172]
### Feature or Bug?
- [x] Feature
- [ ] Bug

### Feature
Typeahead for invites to teams.

#### What would you like?
Currently, all registered users are shown in a dropdown when you try to invite someone to a team. This should be changed to a typeahead field to make it more user friendly.

**Comment by HON95** [comment]
The dropdown has been replaced by a simple text field, to avoid leaking all usernames.
