### ISSUE TITLE
Adding release dates on Tickets

### ISSUE THREAD

**Issue by MathiasFl** [CasualGaming/studlan#174]
### Feature or Bug?
- [x] Feature
- [ ] Bug

### Feature
Add release date on tickets, making it easier for us to set up tickets and releasing them..

#### What would you like?
Adding a datetime field to tickest model, so that they won't be available until that date.

#### How should it work?
If admin dashboard exist, choose date and time from there, else setting date in admin panel wouls suffice. And no tickets should be availabel untill the set date.

**Comment by HON95** [comment]
Already implemented (I don't know when).

**Comment by MathiasFl** [comment]
I did it some time ago, same time as when priority were added
